version: "3.7"

services:
  db:
    # image: arm64v8/mysql:oracle
    container_name: "test_db"
    # platform: linux/amd64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: "myappdb"

    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: "test_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db # Use the service name as the hostname
      - DB_PORT=3306
    depends_on:
      - db
    volumes:
      - .:/app/

networks:
  default:
volumes:
  mysql_data:
